const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function seed() {
  try {
    await prisma.spot.createMany({
      data: [
        {
          spotId: 111,
          parkId: 1,
          spotName: 'Banff Gondola',
          spotDescription: 'High above the town of Banff, you\'ll find yourself on the summit of Sulphur Mountain after 700 metres in elevation. The Banff Gondola is a popular destination for locals and tourists, displaying breathtaking views of Banff and offering dining and other attractions once the summit is reached.',
          spotHourlyRate: 84,
          spotDiscount: 54.6,
          spotLocation: '100 Mountain Ave, Banff, AB T1L 1B2',
        },
        {
          spotId: 112,
          parkId: 1,
          spotName: 'Golden Skybridge',
          spotDescription: 'Walk this suspension bridge 426 feet above an expansive canyon, engulfed by the Columbia Valley.',
          spotHourlyRate: 49,
          spotDiscount: 31.85,
          spotLocation: '503 Golden Donald Upper Road, Golden, BC, V0A 1H0',
        },
        {
          spotId: 113,
          parkId: 1,
          spotName: 'Cave & Basin National Historic Site',
          spotDescription: 'Cave and Basin has been a special place for Indigenous peoples for over ten thousand years and continues to be so to this day. In 1883, three railway workers found the thermal springs, sparking a series of events that led to the creation of Canada’s first national park.',
          spotHourlyRate: 9,
          spotDiscount: 0,
          spotLocation: '311 Cave Ave, Banff, AB T1L 1K2',
        },
        {
          spotId: 114,
          parkId: 1,
          spotName: 'Lake Louise',
          spotDescription: 'Lake Louise is a hamlet in Banff National Park in the Canadian Rockies, known for its turquoise, glacier-fed lake ringed by high peaks and overlooked by a stately chateau.',
          spotHourlyRate: 0,
          spotDiscount: 0,
          spotLocation: 'Lake Louise Lakeshore Trail, Lake Louise, AB T0L',
        },
        {
          spotId: 115,
          parkId: 1,
          spotName: 'Lake Minnewanka',
          spotDescription: 'Lake Minnewanka is a glacial lake in the eastern area of Banff National Park in Canada, about five kilometers northeast of the Banff townsite.',
          spotHourlyRate: 0,
          spotDiscount: 0,
          spotLocation: 'Lake Minnewanka Scenic Dr, Improvement District No. 9, AB T1L 1K2',
        },
        {
          spotId: 116,
          parkId: 1,
          spotName: 'Moraine Lake',
          spotDescription: 'Moraine Lake is a stunning turquoise lake, cradled by the Valley of the Ten Peaks, located in Banff National Park, Alberta, Canada.',
          spotHourlyRate: 0,
          spotDiscount: 0,
          spotLocation: 'Improvement District No. 9, AB',
        },
        {
          spotId: 211,
          parkId: 2,
          spotName: 'Astotin Lake',
          spotDescription: 'Astotin Lake offers a peaceful lakeside setting for your next picnic or family outing.',
          spotHourlyRate: 0,
          spotDiscount: 0,
          spotLocation: 'Improvement District No. 13, AB',
        },
        {
          spotId: 212,
          parkId: 2,
          spotName: 'Geo Domes',
          spotDescription: 'Escape in the wilderness in Elk Island Retreat in these geo domes designed to house a maximum of 2 adults.',
          spotHourlyRate: 249,
          spotDiscount: 0,
          spotLocation: '54371 Range Rd 205, Fort Saskatchewan, AB T8L 3Z3',
        },
        {
          spotId: 311,
          parkId: 3,
          spotName: 'Planetarium and Telescope Combo Tour',
          spotDescription: 'Discover the wonders of the night sky with our award-winning star-gazing tour package!',
          spotHourlyRate: 72.45,
          spotDiscount: 26.25,
          spotLocation: '1 Old Lodge Rd, Jasper, AB T0E 1E0, Canada',
        },
        {
          spotId: 312,
          parkId: 3,
          spotName: 'Columbia Icefield Tour with Glacier Skywalk',
          spotDescription: 'Discover the Glacier Skywalk and Athabasca Glacier aboard an ice explorer vehicle equipped to handle the rugged ice landscape.',
          spotHourlyRate: 124.97,
          spotDiscount: 80.54,
          spotLocation: '93 Icefields Pkwy, Jasper, AB T0E 1E0, Canada',
        },
        {
          spotId: 313,
          parkId: 3,
          spotName: 'Guided Glacier Hike on The Athabasca with IceWalks',
          spotDescription: 'Enjoy the unique experience of walking on a glacier on this small-group tour.',
          spotHourlyRate: 133.34,
          spotDiscount: 69.62,
          spotLocation: '95446QCC+4P4, 95446QCC+4P',
        },
        {
          spotId: 314,
          parkId: 3,
          spotName: 'Maligne Canyon',
          spotDescription: 'A scenic limestone canyon with waterfalls and walking trails.',
          spotHourlyRate: 0,
          spotDiscount: 0,
          spotLocation: 'Maligne Lake Road, Jasper, Jasper National Park, Alberta T0E 1E0 Canada',
        },
        {
            spotId: 315,
            parkId: 3,
            spotName: 'Athabasca Falls',
            spotDescription: 'A spectacular waterfall in Jasper National Park.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Improvement District No. 12, AB T0E 1E0',
          },
          {
            spotId: 316,
            parkId: 3,
            spotName: 'Pyramid and Patricia Lakes',
            spotDescription: 'Subalpine forests and rocky mountain peaks create a stunning background for these two beautiful lakes. The reflection of Pyramid Mountain in the waters of Patricia Lake is a photo worth snapping!',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Pyramid Lake Rd, Jasper, Jasper National Park, Alberta T0E 1E0 Canada',
          },
          {
            spotId: 411,
            parkId: 4,
            spotName: 'Waterton Village',
            spotDescription: 'A historic hamlet in the heart of the Southern Rockies. Embark on a journey of self-discovery just north of the U.S. border.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Waterton, AB T0K 2M0',
          },
          {
            spotId: 412,
            parkId: 4,
            spotName: 'Bears Hump',
            spotDescription: 'Bear\'s Hump Trail is the most popular trail in the Waterton Lakes National Park. The hike offers majestic views of the village and the Waterton Valley.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Waterton Park, AB T0K 2M0, Canada',
          },
          {
            spotId: 413,
            parkId: 4,
            spotName: 'Emerald Bay Scuba Dive',
            spotDescription: 'This sheltered bay is a day use park where scuba divers can explore the wreck of Gertrude, an old logging boat that sank in the bay.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'On the edge of Waterton Townsite, 200 Vimy Ave, Waterton Park, AB T0K 2M0, Canada',
          },
          {
            spotId: 414,
            parkId: 4,
            spotName: 'Prince of Wales Hotel',
            spotDescription: 'The Prince of Wales was built by the Great Northern Railway in 1927 as an extension of the Glacier Park Lodges and today, stays true to its roots.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'AB-5, Waterton Park, AB T0K 2M0',
          },
          {
            spotId: 511,
            parkId: 5,
            spotName: 'Half Day Scenic Float on the Middle Fork of the Flathead River',
            spotDescription: 'This relaxing tour takes place on the boundary to Glacier National Park. Enjoy the scenery as you float and, with luck, spot some wildlife along the way.',
            spotHourlyRate: 75,
            spotDiscount: 55,
            spotLocation: '106 Going-to-the-Sun Rd, West Glacier, MT 59936, USA',
          },
          {
            spotId: 512,
            parkId: 5,
            spotName: 'West Scenic & Polebridge Scenic Driving Tour',
            spotDescription: 'Enjoy comfortable, private transportation and a knowledgeable guide. Learn about the history of the park and valley while enjoying the sights.',
            spotHourlyRate: 764.38,
            spotDiscount: 0,
            spotLocation: '541 Spokane Ave, Whitefish, MT 59937, USA',
          },
          {
            spotId: 513,
            parkId: 5,
            spotName: 'Half-Day Glacier National Park Whitewater Rafting Adventure',
            spotDescription: 'See Glacier National Park in a unique way with this half-day whitewater rafting tour. A guide will be with you throughout the adventure.',
            spotHourlyRate: 121.58,
            spotDiscount: 91.56,
            spotLocation: '12127 US-2, West Glacier, MT 59936, USA',
          },
          {
            spotId: 515,
            parkId: 5,
            spotName: 'East Glacier & Two Medicine Scenic Driving Tour',
            spotDescription: 'Explore East Glacier and Two Medicine areas, witnessing spectacular spots like East Glacier Park Lodge and Two Medicine Lake.',
            spotHourlyRate: 833.86,
            spotDiscount: 0,
            spotLocation: '541 Spokane Ave, Whitefish, MT 59937, USA',
          },
          {
            spotId: 611,
            parkId: 6,
            spotName: 'Gulf Islands Kayak and Seaplane Adventure',
            spotDescription: 'Visit Victoria and its celebrated Buchart Gardens with a local guide. You\'ll visit many of Victoria\'s most celebrated spots on a guided tour.',
            spotHourlyRate: 789,
            spotDiscount: 599,
            spotLocation: 'Pickup is available from all hotels, private residences, and Airbnb in Vancouver.',
          },
          {
            spotId: 612,
            parkId: 6,
            spotName: 'Butchart Gardens & Victoria Tour from Vancouver',
            spotDescription: 'We are hosting cultural immersion retreats in Old Massett Community. Explore the region\'s landscape and learn about the local culture through artful experiences.',
            spotHourlyRate: 274.86,
            spotDiscount: 142.71,
            spotLocation: 'Vancouver Cruise Pier, 999 Canada Pl, Vancouver, BC V6C 3E1, Canada',
          },
          {
            spotId: 711,
            parkId: 7,
            spotName: 'Cultural Immersion & Holistic Wellbeing on Haida Gwaii',
            spotDescription: 'We are hosting cultural immersion retreats in Old Massett Community. Rejuvenate your body and calm your mind through wellness workshops.',
            spotHourlyRate: 6500,
            spotDiscount: 6500,
            spotLocation: 'Airport pickup offered for Masset Airport, Masset, British Columbia of Canada',
          },
          {
            spotId: 811,
            parkId: 8,
            spotName: 'Kootenay National Park Day Tour from Calgary',
            spotDescription: 'Discover a pre-selected mix of walking trails, panoramic viewpoints, and canyon visits during this full-day tour to Kootenay National Park.',
            spotHourlyRate: 210,
            spotDiscount: 205,
            spotLocation: 'Coast Calgary Downtown Hotel & Suites by APA, 610 4 Ave SW, Calgary, AB T2P 0K1, Canada',
          },
          {
            spotId: 812,
            parkId: 8,
            spotName: 'Marble & Johnson Canyon Ice Walk Tour from Calgary/Canmore/Banff',
            spotDescription: 'See the fascinating Marble and Johnston canyons of Banff! Do ice-walking with our local experienced guides and enjoy the gorgeous Canadian Rockies.',
            spotHourlyRate: 155,
            spotDiscount: 155,
            spotLocation: 'Delta Hotels Calgary Downtown, 209 4 Ave SE, Calgary, AB T2G 0C6, Canada',
          },
          {
            spotId: 911,
            parkId: 9,
            spotName: 'Half-Day Whitewater Rafting in Revelstoke',
            spotDescription: 'Enjoy a thrilling white-water rafting experience and admire views of some of British Columbia\'s most spectacular scenery.',
            spotHourlyRate: 173.25,
            spotDiscount: 173.25,
            spotLocation: '12 1 St E, Revelstoke, BC V0E 2S0, Canada',
          },
          {
            spotId: 912,
            parkId: 9,
            spotName: 'Revelstoke Railway Museum',
            spotDescription: 'The museum showcases the historic construction and operation of the Canadian Pacific Railway in Western Canada\'s mountain region.',
            spotHourlyRate: 14,
            spotDiscount: 4,
            spotLocation: '719 Track St W, Revelstoke, BC.',
          },
          {
            spotId: 913,
            parkId: 9,
            spotName: 'The Enchanted Forest',
            spotDescription: 'The Enchanted Forest theme park is situated in one of the BC\'s beautiful old growth forests located midway between Revelstoke, BC and Sicamous, BC.',
            spotHourlyRate: 11.2,
            spotDiscount: 7.2,
            spotLocation: '7060 Trans-Canada Hwy, Revelstoke, BC V0E 2S0',
          },
          {
            spotId: 1011,
            parkId: 10,
            spotName: 'Ucluelet Harbour Tour',
            spotDescription: 'Immerse yourself in some of British Columbia’s most spectacular seascapes—and enjoy an active way to explore—on this small-group, half-day Ucluelet Harbour kayaking tour.',
            spotHourlyRate: 110,
            spotDiscount: 99,
            spotLocation: '200 Hemlock St, Ucluelet, BC V0R 3A0, Canada',
          },
          {
            spotId: 1012,
            parkId: 10,
            spotName: 'Cowichan Bay Half Day Whale & Wildlife Adventure',
            spotDescription: 'Gain a new perspective on Vancouver with a whale-watching tour through the Gulf Islands. Going with a guide ensures you see wildlife difficult to spot if on your own.',
            spotHourlyRate: 201.25,
            spotDiscount: 157.02,
            spotLocation: '1721 Cowichan Bay Rd, Cowichan Bay, BC V0R 1N0, Canada',
          },
          {
            spotId: 1013,
            parkId: 10,
            spotName: 'Radar Hill',
            spotDescription: 'As the site of a historic radar station during World War II, this short, picturesque walk features the Kap\'Yong Memorial – in honour of the 2nd Battalion Princess Patricia\'s Canadian Light Infantry.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Alberni-Clayoquot, BC V0R 2Z0',
          },
          {
            spotId: 1014,
            parkId: 10,
            spotName: 'Combers Beach',
            spotDescription: 'Located in Pacific Rim National Park, Combers Beach is a beautiful beach area on Vancouver Island that is particularly popular with surfers. The trail to the beach is short but steep.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Alberni-Clayoquot, BC',
          },
          {
            spotId: 1015,
            parkId: 10,
            spotName: 'Bog Trail',
            spotDescription: 'On this trail one walks on a level boardwalk that rests upon the bog surface. The trail is wheelchair accessible and pets are allowed provided they keep their owners on a leash.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Alberni-Clayoquot, BC V0R 3A0',
          },
          {
            spotId: 1111,
            parkId: 11,
            spotName: 'Emerald Lake',
            spotDescription: 'Known as “Rainbow Lake” by the First Nations, Emerald Lake offers a breathtaking view on its truly emerald-green water surrounded by Surprise Mountain and Mt Gilliam.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Emerald Lake Road, Yoho National Park, British Columbia V0A 1G0 Canada',
          },
          {
            spotId: 1112,
            parkId: 11,
            spotName: 'Takakkaw Falls',
            spotDescription: 'Takakkaw Falls is the tallest waterfall in the Canadian Rockies and the second-tallest in Canada. The cascading water creates picturesque mist through the pines.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Yoho National Park, Field, BC V0A 1G0',
          },
          {
            spotId: 1113,
            parkId: 11,
            spotName: 'Kicking Horse River',
            spotDescription: 'Rising from the ice-cold glacial waters of Wapta Lake, Kicking Horse falls steeply in its upper reaches before widening onto a flattened valley floor.',
            spotHourlyRate: 0,
            spotDiscount: 0,
            spotLocation: 'Columbia-Shuswap, BC',
          },
      ],
    });

    console.log('Spots seeded successfully!');
  } catch (error) {
    console.error('Error seeding spots:', error);
  } finally {
    await prisma.$disconnect();
  }
}

seed();
